schema_version = "1.0.0"

id = "PieMenuEditor"
version = "1.18.8"
name = "Pie Menu Editor"
tagline = "Shape your Blender workflow with customizable pies, menus, macros, modals, and more"
maintainer = "Pluglug, Razed, Roaoao"
type = "add-on"

website = "https://github.com/Pluglug/pie-menu-editor-fork"

tags = ["User Interface"]

blender_version_min = "4.2.0"
blender_version_max = "4.7.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
